### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 14.

### ISSUE THREAD

**Issue by mustuni1** [octalmage/robotjs#119]
I am trying to use robotjs in an electron app, and am receiving this error when I require the library: 

    Uncaught Exception:
    Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/test/Downloads/photon-0.1.2-alpha/node_modules/robotjs/index.js:1:97)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

Any suggestions on how to fix this?

**Comment by octalmage** [comment]
Usually this means the module wasn't compiled for electron, or the correct version of electron.

**Comment by octalmage** [comment]
See this document:

https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

Let me know if this helps!

**Comment by octalmage** [comment]
I'm going to close this issue, but please let me know if you're still having issues!

**Comment by BrainyBrian** [comment]
Still getting Expecting 50, getting 48 error. It used to be expecting 50 got 14...
