### ISSUE TITLE
Linux build failing

### ISSUE THREAD

**Issue by ayhankuru** [octalmage/robotjs#131]
```sh
> robotjs@0.3.3 install /home/cobaimelan/proje/robotjs
> node-gyp rebuild

make: `/home/cobaimelan/proje/robotjs/build' dizine giriliyor
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
make: g++: Komut bulunamadı
make: *** [Release/obj.target/robotjs/src/robotjs.o] Hata 127
make: `/home/cobaimelan/proje/robotjs/build' dizininden çıkılıyor
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/cobaimelan/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-68-generic
gyp ERR! command "/home/cobaimelan/.nvm/versions/node/v5.0.0/bin/node" "/home/cobaimelan/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cobaimelan/proje/robotjs
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/home/cobaimelan/.nvm/versions/node/v5.0.0/bin/node" "/home/cobaimelan/.nvm/versions/node/v5.0.0/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! robotjs@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1

```
npm-debug.log

https://gist.github.com/ayhankuru/ccbdaedf5209fbc98ab6

**Comment by Deltatiger** [comment]
This is saying something like g++ command not found ```g++: Komut bulunamadı```.
Please follow this : https://github.com/octalmage/robotjs#installation

**Comment by ayhankuru** [comment]
@Deltatiger yeah, I'm sorry my mistake

**Comment by Deltatiger** [comment]
@ayhankuru  No problem. Update the issue if something else fails

**Comment by ayhankuru** [comment]
@Deltatiger ı'm close that issue not problem any more :/
