### ISSUE TITLE
Version mismatch when using in nwjs

### ISSUE THREAD

**Issue by caffaware** [octalmage/robotjs#233]
Hi, I'm trying to include robotjs in a nwjs app and after installing via npm install robotjs I get a version mismatch error. Can you help me ?

module.js:625
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 49.
    at Error (native)
    at Object.Module._extensions..node (module.js:625:18)
    at Module.load (module.js:497:32)
    at tryModuleLoad (module.js:456:12)
    at Function.Module._load (module.js:448:3)
    at Module.require (module.js:507:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/test/node_modules/robotjs/index.js:1:77)
    at Module._compile (module.js:580:32)
    at Object.Module._extensions..js (module.js:595:10)

**Comment by octalmage** [comment]
Hi there! With NW.js you need to rebuild the module. You can read more about this here:

https://github.com/nwjs/nw.js/wiki/build-native-modules-with-nw-gyp

I hope this helps!

**Comment by caffaware** [comment]
Awesome, yup it worked. I had to build it with nw-gyp using the following commands !
sudo npm install nw-gyp -g
sudo nw-gyp configure --target=0.17.1 (0.17.1 = nwjs version) (in the robotjs folder)
sudo nw-gyp build --target=0.17.1

Thanks for your help ! Keep up the good work with your module

**Comment by octalmage** [comment]
Awesome glad it worked! I'll get something added to the readme.

**Comment by octalmage** [comment]
I created #236 to handle the docs.
