### ISSUE TITLE
nw-gyp rebuild --target=0.18.2 fails for robotjs

### ISSUE THREAD

**Issue by maltheism** [octalmage/robotjs#243]
I apologize in advanced as I'm not aware if the issue is with nw-gyp or robotjs.

On macOS Sierra Version 10.12

I'm not able to rebuild robotjs for a nwjs project(nwjs-sdk-v0.18.2-osx-x64) by using nw-gyp rebuild.

Steps to reproduce:
cd node_modules/robotjs
sudo nw-gyp configure --target=0.18.2
sudo nw-gyp rebuild --target=0.18.2

```
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@6.8.1 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/intralizee/Development/GitHub/Private/nodejs/Lyrics.fish/node_modules/robotjs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/intralizee/.nw-gyp/0.18.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/intralizee/.nw-gyp/0.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/nw-gyp',
gyp info spawn args   '-Dnode_lib_file=nw.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/intralizee/Development/GitHub/Private/nodejs/Lyrics.fish/node_modules/robotjs',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
In file included from ../src/robotjs.cc:1:
In file included from /Users/intralizee/.nw-gyp/0.18.2/src/node.h:42:
/Users/intralizee/.nw-gyp/0.18.2/deps/v8/include/v8.h:3462:26: error: no member named 'unique_ptr' in namespace 'std'
  typedef std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
                    ~~~~~^
/Users/intralizee/.nw-gyp/0.18.2/deps/v8/include/v8.h:3462:37: error: expected expression
  typedef std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
                                    ^
/Users/intralizee/.nw-gyp/0.18.2/deps/v8/include/v8.h:3462:53: error: expected member name or ';' after declaration specifiers
  typedef std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
  ~~~~~~~                                           ^
/Users/intralizee/.nw-gyp/0.18.2/deps/v8/include/v8.h:3464:3: error: unknown type name 'SerializedModule'
  SerializedModule Serialize();
  ^
/Users/intralizee/.nw-gyp/0.18.2/deps/v8/include/v8.h:3466:31: error: unknown type name 'SerializedModule'
      Isolate* isolate, const SerializedModule& serialized_data);
                              ^
5 errors generated.
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/nw-gyp" "rebuild" "--target=0.18.2"
gyp ERR! cwd /Users/intralizee/Development/GitHub/Private/nodejs/Lyrics.fish/node_modules/robotjs
gyp ERR! node -v v6.8.1
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok 
```

I'm able to successfully rebuild robotjs for nwjs v0.14.7 but I want to eventually move to latest version of nwjs and this is only hiccup that i'm having.

**Comment by octalmage** [comment]
Hi @intralizee! 

It looks like this could be an issue for Macs. Could you try this branch? 

https://github.com/octalmage/robotjs/tree/c%2B%2B11

Personally I feel like this might be a nw-gyp issue. This doesn't seem to be an issue when I compile for Node v6.8.1 using node-gyp, but it fails for nw-gyp. 

Anyway, let me know if this works!

**Comment by intralizee** [comment]
Hi @octalmage 

That branch works for me! Thanks :)

My terminal output if useful:
```
rvr35101artdesignwifi126:robotjs intralizee$ sudo nw-gyp configure --target=0.18.2
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@6.9.1 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/intralizee/robotjs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/intralizee/.nw-gyp/0.18.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/intralizee/.nw-gyp/0.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/nw-gyp',
gyp info spawn args   '-Dnode_lib_file=nw.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/intralizee/robotjs',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
rvr35101artdesignwifi126:robotjs intralizee$ sudo nw-gyp rebuild --target=0.18.2
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@6.9.1 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/intralizee/robotjs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/intralizee/.nw-gyp/0.18.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/intralizee/.nw-gyp/0.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/nw-gyp',
gyp info spawn args   '-Dnode_lib_file=nw.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/intralizee/robotjs',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
  CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
  CC(target) Release/obj.target/robotjs/src/mouse.o
  CC(target) Release/obj.target/robotjs/src/keypress.o
  CC(target) Release/obj.target/robotjs/src/keycode.o
  CC(target) Release/obj.target/robotjs/src/screen.o
  CC(target) Release/obj.target/robotjs/src/screengrab.o
  CC(target) Release/obj.target/robotjs/src/snprintf.o
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  SOLINK_MODULE(target) Release/robotjs.node
gyp info ok
```

**Comment by octalmage** [comment]
Fantastic! I found the solution here: 

https://github.com/nodejs/node-gyp/issues/291

I'll probably merge that branch after confirming that it doesn't cause any issues.

**Comment by octalmage** [comment]
It looks like this only works for Node 6:

https://travis-ci.org/octalmage/robotjs/builds/170140159

**Comment by intralizee** [comment]
I'm able to build with Node 7 that was just released.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
