### ISSUE TITLE
npm install not working on Windows 7 SP1

### ISSUE THREAD

**Issue by modulexcite** [octalmage/robotjs#256]
## Expected Behavior
Expect **robotjs** to be installed in a project or be able to build it from **robotjs** source code after cloning it.

## Current Behavior
It returns the following error when executing `npm install` after cloning the project or running `npm install` inside another project which has **robotjs** as a dependency.
```
npm install

> robotjs@0.4.5 install E:\robotjs
> prebuild --install

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v140 (Platform Toolset = 'v140' ) cannot be found. To build using the v140 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". In stall v140 to build using the v140 build tools. [E:\robotjs\build\robotjs.vcxproj]
prebuild ERR! build error
prebuild ERR! stack Error: `msbuild` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onExit (E:\robotjs\node_modules\node-gyp\lib\build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
prebuild ERR! not ok
prebuild ERR! build Error: `msbuild` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onExit (E:\robotjs\node_modules\node-gyp\lib\build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\mattjs\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! robotjs@0.4.5 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the robotjs@0.4.5 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\robotjs\npm-debug.log
```

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Clone this project
2. cd to the location
3. npm install

## Context
I'm trying to build [screencat](https://github.com/maxogden/screencat) from the source on a windows machine as the project doesn't have an official windows release but can't get it to work either by installing via `npm install` or `node-gyp rebuild --python "path-to-python" --msvs_version=2015`

## Your Environment
* RobotJS version: 0.4.5
* Node.js version: 6.9.2 32-bit
* npm version: 4.0.5
* node-gyp version: 3.4.0
* Python version: 2.7
* Visual Studio: 2015 Professional Update 3
* Operating System: Windows 7 SP1 64-bit

**Comment by octalmage** [comment]
This should be resolved by v0.4.6, please let me know if you still encounter this and we can reopen the issue.
