### ISSUE TITLE
Failing to install on windows 10, x64, node 8.8.0

### ISSUE THREAD

**Issue by Glutch** [octalmage/robotjs#338]
Hello! Seems like a great package, would love to get it working!

What i've done so far to try to fix it
Installed python 2.7.14
npm install prebuild-install node-gyp rebuild -g
(and i already have the majority of .net stuff installed since i do a lot of c# work)

* RobotJS version: Trying to install latest "npm install robotjs"
* Node.js version: 8.8.0
* npm version: 5.5.1
* Operating System: Windows 10 x64

> Full error

```
C:\Users\glutch\Documents\Node\whisper>npm install robotjs

> robotjs@0.4.7 install C:\Users\glutch\Documents\Node\whisper\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds\robotjs-v0.4.7-node-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\glutch\AppData\Roaming\npm-cache\_prebuilds\https-github.com-octalmage-robotjs-releases-download-v0.4.
7-robotjs-v0.4.7-node-v57-win32-x64.tar.gz
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-win32-x64.tar.gz
prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.8.0 runtime=node arch=x64 platform=win32)

C:\Users\glutch\Documents\Node\whisper\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Users\glutch\AppData\Roaming\npm\node_modules\npm\bin\node-
gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual S
tudio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\glutch\Documents\Node\whisper\node_modules\robotjs\
build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\glutch\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\glutch\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\Users\glutch\Documents\Node\whisper\node_modules\robotjs
gyp ERR! node -v v8.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN whisper@1.0.0 No description
npm WARN whisper@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\glutch\AppData\Roaming\npm-cache\_logs\2017-10-25T17_21_00_281Z-debug.log
```

**Comment by Glutch** [comment]
Installed nvm-windows, downgraded to node 6.11.5. Now working

**Comment by Glutch** [comment]
Installed nvm-windows, downgraded to node 6.11.5. Now working

**Comment by isrmicha** [comment]
@Glutch  thanks, solved my problem

**Comment by jareddgotte** [comment]
@Glutch @isrmicha I had similar issues until I found **Option 1** in the [node-gyp readme](https://github.com/nodejs/node-gyp#option-1). Now I've got robotjs 0.4.7 ([commit d021733](https://github.com/octalmage/robotjs/commit/d0217334ddae79ff7d07046b8f65d43597a8044a)) running on Windows 10 x64, Node.js 9.3.0, and npm 5.5.1.

**Comment by oktapodia** [comment]
That should be solved with the latest release

**Comment by exejutable** [comment]
> That should be solved with the latest release

The issues persists Windows 10, x64 and nodejs v10.16.3
