### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed when building robotjs and electron

### ISSUE THREAD

**Issue by UttakarshTikku** [octalmage/robotjs#364]
I am trying to build robotjs and electron app using electron but failing to do so. Some DLL is apparently missing. 
I have already tried rebuilding electron but that hasn't made any difference.
Here is the stacktrace:

"App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\<dirname>\node_modules\robotjs\build\Release\robotjs.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)"

**Comment by LeoMartinDev** [comment]
`npm i --save-dev electron-rebuild`
`./node_modules/.bin/electron-rebuild`

**Comment by UttakarshTikku** [comment]
Thanks a lot! That worked like a charm!

**Comment by octalmage** [comment]
Great!
