### ISSUE TITLE
error installing npm in windows 10

### ISSUE THREAD

**Issue by brakdag** [octalmage/robotjs#398]
```npm i robotjs``` don't work
not install in windows 10 

## Possible Solution
not idea

## Your Environment
* RobotJS version: npm version last
* Node.js version: 9
* npm version: 8.11.2
* Operating System: Windows 10 Home 64x

**Comment by antoniojps** [comment]
Try to install node-gyp globally:
`npm install -g node-gyp`

Then try installing the package again:
`npm install robotjs`

This solved the issue for me.

**Comment by zircuitz** [comment]
I am having issues as well. Same Windows as @brakdag 
I did install all the packages as @antoniojps mentions here. But when I try to initialize the library, I still get an error message:

```
Uncaught Exception: 
Error: A dynamic link library (DLL) initialization routine failed. 
    at process.module.(anomjmous function) [as dlopen] (ELECTRON 
    at Object.ModuIe._extensions..node 
    at Object.module.(anonymous function) [as .node] (ELECTRON 
    at Module.load 
    at tryModuIeLoad 
    at Function.ModuIe._Ioad (module.js:4963) 
    at Module.require 
    at require (internal/module.js:11:18) 
    at 
(C: \ Users\AIexa n d 170) 
at Object. < anonymous> 
```

**Comment by sbucaille** [comment]
Same here, can't install robotjs, I did what @antoniojps advised, the 3 commands, here is the last one : 
![image](https://user-images.githubusercontent.com/24275548/40878505-9bf6ea68-6692-11e8-8a8b-fbe7d89a96f4.png)

Someone knows where does it come from ?

Thanks a lot :)

**Comment by Deltatiger** [comment]
This seems to be a problem with the version requirements for NodeJS recompiled binaries.
The latest release does not have binaries for Windows 10 64Bit. When the node-pre-gyp fails due to lack of binaries, it falls back to building robotjs. For that you need some prerequisites, which are listed in the readme (https://github.com/octalmage/robotjs#building). 
Can you try installing the required items and then trying again?

**Comment by lgh06** [comment]
try:
```
npm install robotjs --force
```
then go to \node_modules\robotjs, 
```
node-gyp configure --msvs_version=2015 --arch-ia32
```

install windows-build-tools first.

**Comment by lgh06** [comment]
cannot install either.
win10: 1803 17134.5
node: v8.11.1
npm: 5.6.0


```
C:\Users\liu\.node-gyp\8.11.1\x64\node.lib : fatal error LNK1127: library is corrupt [F:\dev\robot\node_modules\robotjs
\build\robotjs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\dev\robot\node_modules\robotjs
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by lgh06** [comment]
it worked, after I install a newer nodejs 8.11.3

**Comment by pramodDesign** [comment]
When I try to run my project got following error:

**Comment by Deltatiger** [comment]
@pramodDesign What did you try to run? Could you give us more information?

**Comment by A-312** [comment]
@pramodDesign 

> 19 error node v5.6.0
> 20 error npm v3.6.0

You've old version and you need to "have the latest version of node.js and npm installed."

**Comment by Kilometres** [comment]
I had the exact same problem, I tried the stable build the latest build and all the sorts. But i was using node x64 bit, uninstall that and download node x86 (32 bit). It seems to solve the problems and has not caused me an error since. Hope this helps.

Ran the one command:
`npm install robotjs`

PC Specs:
System Type: 64-bit Operating System, x4-based processor
Operating System: Windows 10 Pro

**Comment by AirFusion45** [comment]
As of today, the latest windows build tools (5.1.0) freezes after installing python. 
![image](https://user-images.githubusercontent.com/23324711/57991363-2a355500-7a63-11e9-9f4f-9a055c599b3f.png)
So use version 4.0.0 instead of 5.1.0 -> `npm install --global --production windows-build-tools@4.0.0`

**Comment by lucasctd** [comment]
> **It might be worth updating Node before doing the instructions below.**
> 
> Run this command from an administrative shell to install the "software" dependencias (Visual Studio, Python) on windows:
> `npm install --global --production windows-build-tools`
> 
> Install node-gyp globally:
> `npm install -g node-gyp`
> 
> Then try installing the package again:
> `npm install robotjs`
> 
> This solved the issue for me.

@antoniojps It does not work for me. I always get the same error:

![image](https://user-images.githubusercontent.com/5876679/60051994-a21e1d00-96aa-11e9-8f18-e9416687fde8.png)
It seems I can't install robotjs on windows...

**Comment by blizzard190** [comment]
For the people who can't install robotjs because of node-gyp, I've been able to fix it by downloading node version 10. The person who told me this way of fixing it, told me that the npm install for this libary uses a file that is nolonger included in node version 12, for this reason downloading an older version seems to fix it. I can't remember the source so sorry for that. 

@lucasctd I had the same error the method above worked for me but I would check your node version first before trying it.

ps: I did this for windows, I have no clue if this will work for other systems.

**Comment by Tymski** [comment]
Finally, after 2 years I found a solution that works for me:
npm install -g windows-build-tools
instead of
npm install --global --production windows-build-tools

**Comment by evertdhont** [comment]
@Tymski this looks like the way to go! After installing it several times it finally installed correctly. Thanks!

**Comment by AfzalivE** [comment]
For anyone still having a problem with this:

- Use NodeJS 10 (LTS)
- Try `npm install -g windows-build-tools --vs2017`

**Comment by oktapodia** [comment]
The support will be improved in the near next release

**Comment by liketurbo** [comment]
1. Please use `nvm` and switch to the version `node@8`
2. Complete installation of all prerequisites from [node-gyp](https://github.com/nodejs/node-gyp)

**Comment by Tymski** [comment]
Another thing you can try is to install node-gyp locally as a development dependency
```
npm i --save-dev node-gyp
```
`npm i robotjs`  works for me after that (remember to run as administrator)

**Comment by ShawnMeister** [comment]
I tried running Node14.15.1 and I was getting this error.

If you have node installed on windows as an actual app do the following steps to get rid of this error.

1. uninstall nodejs from add or remove programs
2. install nvm globally and  install/use node version 12.0.0 ( https://github.com/nvm-sh/nvm#installing-and-updating )
3. npm i robotjs

Fool proof.

Cheers

**Comment by Tymski** [comment]
@ShawnMeister you link a solution for Linux/Max (https://github.com/nvm-sh/nvm#installing-and-updating) whereas this issue is for Windows 10

**Comment by ShawnMeister** [comment]
> @ShawnMeister you link a solution for Linux/Mac  
> (https://github.com/nvm-sh/nvm#installing-and-updating)  
> "nvm is a for Mac/Linux only"  
>  whereas this issue is for Windows 10  
> "error installing with npm in **windows 10**"  

Ahh my mistake. I edited it

**Comment by Abuzbek** [comment]
> 

how to do this in mac os

**Comment by Satish-Thapa** [comment]
> **It might be worth updating Node before doing the instructions below.**
> 
> Run this command from an administrative shell to install the "software" dependencias (Visual Studio, Python) on windows: `npm install --global --production windows-build-tools`, recent feedback has been using `npm install -g windows-build-tools` as an alternative.
> 
> Install node-gyp globally: `npm install -g node-gyp`
> 
> Then try installing the package again: `npm install robotjs`
> 
> This solved the issue for me.

npm install --global --production windows-build-tools now its change to this npm install -g node-gyp and node-gyp rebuild

**Comment by ftyszyx** [comment]
Robotjs (https://github.com/octalmage/robotjs)is build use V8 API.So it must be rebuilt for different Node versions.
This is a big trouble when installing on a platform that has no build environment..
So I rewrapped Robotjs with Node API and prebuilt it. Now you can install robotjs_addon with just one command 
npm install robotjs_addon
And it is compatible with different Node versions. It's open source. You can check it out if you are interested.https://github.com/ftyszyx/robotjs
Warm: some api is removed,because there is no need for me, you can help to improve.

**Comment by octalmage** [comment]
Closing stale issues as part of a cleanup. If this is still an issue, please reopen and I'll take a look. Thanks!
