### ISSUE TITLE
Issue on installing RobotJs

### ISSUE THREAD

**Issue by lmnyx** [octalmage/robotjs#410]
```
D:\projs\aaaa>npm -version
6.2.0

D:\projs\aaaa>node -v
v10.8.0

D:\projs\aaaa>node-gyp --version
v3.7.0

D:\projs\aaaa>npm i robotjs

> canvas@1.6.9 install D:\projs\aaaa\node_modules\canvas
> node-gyp rebuild


D:\projs\aaaa\node_modules\canvas>if not defined npm_config_node_gyp (node "D:\P
rogram Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..
\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Fil
es\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_m
ain.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\generator\msvs.py", line 2004, in GenerateOutput
    generator_flags))
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\generator\msvs.py", line 943, in _GenerateProject
    return _GenerateMSVSProject(project, options, version, generator_flags)
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\generator\msvs.py", line 1047, in _GenerateMSVSProject
    p.WriteIfChanged()
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\MSVSProject.py", line 208, in WriteIfChanged
    encoding="Windows-1252")
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\easy_xml.py", line 122, in WriteXmlIfChanged
    xml_string = xml_string.decode(default_encoding).encode(encoding)
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 507-523:
 character maps to <undefined>
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:238:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projs\aaaa\node_modules\canvas
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok

> robotjs@0.5.1 install D:\projs\aaaa\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.8.0 runtime=
node arch=x64 platform=win32)

D:\projs\aaaa\node_modules\robotjs>if not defined npm_config_node_gyp (node "D:\
Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\.
.\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Fi
les\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_m
ain.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\generator\msvs.py", line 2004, in GenerateOutput
    generator_flags))
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\generator\msvs.py", line 943, in _GenerateProject
    return _GenerateMSVSProject(project, options, version, generator_flags)
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\generator\msvs.py", line 1047, in _GenerateMSVSProject
    p.WriteIfChanged()
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\MSVSProject.py", line 208, in WriteIfChanged
    encoding="Windows-1252")
  File "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\easy_xml.py", line 122, in WriteXmlIfChanged
    xml_string = xml_string.decode(default_encoding).encode(encoding)
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 509-525:
 character maps to <undefined>
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:238:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projs\aaaa\node_modules\robotjs
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN aaaa@2.2.8 No description
npm WARN aaaa@2.2.8 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 (node_modules\canva
s):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 install: `node-gyp
rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\СуперДуперГовнище\AppData\Roaming\npm-cache\_logs\2018-08-
06T06_43_54_448Z-debug.log

D:\projs\aaaa>```

What i have to do? Windows7 Ultimate

**Comment by entozoon** [comment]
Same here - can't run on Node v10.8.0

**Comment by emko** [comment]
have any of you figured out how to run it on node 10?

**Comment by Deltatiger** [comment]
It is working for me on NodeJS 10.
My environment is Windows 7 64 bit + Node 10.10 + Latest RobotJS Version.

**Comment by Fairnia** [comment]
Installing windows-build-tools is what did it for me, thanks!

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
