### ISSUE TITLE
Can't install robotjs

### ISSUE THREAD

**Issue by lffg** [octalmage/robotjs#418]
Hi,

I'm trying to install the robotjs, but I could not, after trying several times on my Windows 10 computer.
I also think that it's important to mention that I have already installed Python version 2.7.

The error in CMD:
```shell
> robotjs@0.5.1 install C:\Users\luizf\Desktop\proj\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.1 runtime=node arch=x64 platform=win32)

C:\Users\luizf\Desktop\proj\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\luizf\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\luizf\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\luizf\Desktop\proj\node_modules\robotjs
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN proj@1.0.0 No description
npm WARN proj@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\luizf\AppData\Roaming\npm-cache\_logs\2018-09-15T03_07_38_201Z-debug.log
```

The installation log can be found below:  
https://gist.github.com/lffg/2ad3575f919210c08ed9d661fca86840

---

Please comment if you need any more information.

Thanks in advance.

**Comment by emko** [comment]
anyone know how to get this working on node 10?

**Comment by lffg** [comment]
Hi, thanks for the reply.

I already tried this, but the error continues as I showed above.

Thanks,

**Comment by Deltatiger** [comment]
@lffg By any chance do you have VS 2017 installed?

This issue has similar / same error stack as yours.
https://github.com/nodejs/node-gyp/issues/1144

**Comment by lffg** [comment]
Yes, I have it.

**Comment by budhader01** [comment]
hi Iffg,

Did you find the solution for the above issue which you mentioned?

I am also facing the same issue and eagerly looking for a solution.

Thanks

**Comment by IndyVC** [comment]
Why did u close this issue? How did you solve it?

**Comment by rafaelconcept** [comment]
npm install -g windows-build-tools
