### ISSUE TITLE
Unable to use robotjs with electron

### ISSUE THREAD

**Issue by Dan5741** [octalmage/robotjs#428]
Hello! I am trying to create an electron app that uses robotjs. I get the following error when I try to start it:

## Expected Behavior
Open a browser window and load my html file.

## Current Behavior
App threw an error during load
Error: The specified procedure could not be found.
\\?\C:\Users\Daniel\Desktop\TriggerBot with UI\node_modules\robotjs\build\Release\robotjs.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Daniel\Desktop\TriggerBot with UI\node_modules\robotjs\index.js:1:170)
    at Object.<anonymous> (C:\Users\Daniel\Desktop\TriggerBot with UI\node_modules\robotjs\index.js:38:3)

Environment:
RobotJS version: 0.5.1
Node.js version: 10.11.0
npm version: 6.4.1
electron:1.8.8
Operating System: win10 x64

**Comment by Dan5741** [comment]
> have you tried this steps ?
> https://robotjs.io/docs/electron

Yes I did and the build fails.

**Comment by mrarticuno** [comment]
Try this:
`npm rebuild --runtime=electron --target=1.8.8 --disturl=https://atom.io/download/atom-shell --abi=48`

**Comment by Dan5741** [comment]
That worked thank you!

**Comment by Deltatiger** [comment]
Closing this issue. We can reopen the issue if required.
