### ISSUE TITLE
error on node v8.9.3 on installing

### ISSUE THREAD

**Issue by pg07codes** [octalmage/robotjs#430]
## Expected Behavior
npm install robotjs should install and download the required prebuilt binary

## Current Behavior
this error comes on installing via npm--

```

C:\Users\iampr\WebstormProjects\testing> npm install robotjs

> robotjs@0.5.1 install C:\Users\iampr\WebstormProjects\testing\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.9.3 runtime=node arch=x64 platform=win32)

C:\Users\iampr\WebstormProjects\testing\node_modules\robotjs>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\iampr\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\iampr\WebstormProjects\testing\node_modules\robotjs
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN testing@1.0.0 No description
npm WARN testing@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\iampr\AppData\Roaming\npm-cache\_logs\2018-10-11T01_48_27_203Z-debug.log

```

## Possible Solution
no idea.

## Steps to Reproduce (for bugs)
npm install robotjs on windows 10 64bit

## Your Environment

* RobotJS version: latest
* Node.js version: 8.9.3
* npm version:5.5.1
* Operating System:windows

**Comment by Deltatiger** [comment]
Could you check and tell if you have a the dependencies [https://github.com/octalmage/robotjs#building].

I think this could be an issue due to the lack of pre-built binaries for the 64 bit Windows.

**Comment by pg07codes** [comment]
@Deltatiger Thanks. Are the new versions of Visual Studio supported or i have to install the 2013 one ?

**Comment by pg07codes** [comment]
Thanks a lot  @Deltatiger . i got it working. amazing library. 😄
