### ISSUE TITLE
Unexpected character '�' (1:0) while parsing ./node_modules/robotjs/build/Release/robotjs.node

### ISSUE THREAD

**Issue by ZhukovGeorge** [octalmage/robotjs#452]
## Current Behavior
When running my app with installed robotjs
SyntaxError: Unexpected character '�' (1:0) while parsing /Users/george/IdeaProjects/chrome-extension-automation/node_modules/robotjs/build/Release/robotjs.node while parsing file: /Users/george/IdeaProjects/chrome-extension-automation/node_modules/robotjs/build/Release/robotjs.node
    at DestroyableTransform.end [as _flush] (/Users/george/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/insert-module-globals/index.js:114:21)
    at DestroyableTransform.prefinish (/Users/george/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at prefinish (/Users/george/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/Users/george/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/Users/george/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/Users/george/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/Users/george/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
    at endReadableNT (/Users/george/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Context
I am running it in order of automated test for cypress.

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: v8.9.1
* npm version: 5.5.1
* cypress vesrion: 3.1.4
* Operating System: mac os

**Comment by hello-chenchen** [comment]
the same issue to me

    ERROR in ./node_modules/robotjs/build/Release/robotjs.node 1:0
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/robotjs/index.js 1:14-53

Your Environment
webpack version: 4.0
electron version: 4.0.1

RobotJS version: 0.5.1
Node.js version: v10.13.0
npm version: 6.4.1
cypress vesrion: 
Operating System: mac os

**Comment by hello-chenchen** [comment]
still not work in windows

**Comment by hello-chenchen** [comment]
finally, it works for me, by using webpack node-loader to build the source code, and the demo code just like below:
    `
    var Screen = require('robotjs');
    var screenSize = Screen.getScreenSize();
    console.log(JSON.stringify(screenSize));
    `
   [demo](https://github.com/hello-chenchen/system-operate-tools/tree/es2015-gyp-robotjs)
this is a demo link for u

**Comment by ZhukovGeorge** [comment]
Looks like the cypress@3.1.4 uses the not compatible version of the electron

**Comment by hello-chenchen** [comment]
you mean that you have fixed this issue by downgrade the cypress version?

**Comment by oktapodia** [comment]
It looks like this issue has been solved.
You may reopen this issue if it has been closed in error.

**Comment by twotabsofacid** [comment]
If anyone gets here looking for a solution specifically for using RobotJS with Electron (like I did), this is it: http://robotjs.io/docs/electron
