### ISSUE TITLE
win / node v12 / rebuild error

### ISSUE THREAD

**Issue by karacas** [octalmage/robotjs#475]
```
λ npx node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.1.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'd:\\tmp\\zzz\\robotjs\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'd:\\tmp\\zzz\\robotjs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'd:\\tmp\\zzz\\robotjs\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\der2\\.node-gyp\\12.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\der2\\.node-gyp\\12.1.0',
gyp info spawn args   '-Dnode_gyp_dir=d:\\tmp\\zzz\\robotjs\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\der2\\.node-gyp\\12.1.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=d:\\tmp\\zzz\\robotjs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'd:\\tmp\\zzz\\robotjs\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn msbuild
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  robotjs.cc
  win_delay_load_hook.cc
d:\tmp\zzz\robotjs\src\os.h(26): warning C4005: 'STRICT': macro redefinition (compiling source file ..\src\robotjs.cc) [d:\tmp\zz z\robotjs\build\robotjs.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\minwindef.h(23): note: see previous definition of 'STRICT' (compiling so
  urce file ..\src\robotjs.cc)
..\src\robotjs.cc(63): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotjs .vcxproj]
..\src\robotjs.cc(63): error C2789: 'x': an object of const-qualified type must be initialized [d:\tmp\zzz\robotjs\build\robotjs. vcxproj]
  ..\src\robotjs.cc(63): note: see declaration of 'x'
..\src\robotjs.cc(64): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotjs .vcxproj]
..\src\robotjs.cc(64): error C2789: 'y': an object of const-qualified type must be initialized [d:\tmp\zzz\robotjs\build\robotjs. vcxproj]
  ..\src\robotjs.cc(64): note: see declaration of 'y'
..\src\robotjs.cc(97): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotjs .vcxproj]
..\src\robotjs.cc(98): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotjs .vcxproj]
..\src\robotjs.cc(114): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(115): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(143): error C2661: 'v8::Value::ToString': no overloaded function takes 0 arguments [d:\tmp\zzz\robotjs\build\ro botjs.vcxproj]
..\src\robotjs.cc(143): error C2512: 'v8::String::Utf8Value::Utf8Value': no appropriate default constructor available [d:\tmp\zzz \robotjs\build\robotjs.vcxproj]
..\src\robotjs.cc(159): error C2661: 'v8::Value::BooleanValue': no overloaded function takes 0 arguments [d:\tmp\zzz\robotjs\buil d\robotjs.vcxproj]
..\src\robotjs.cc(239): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(251): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(252): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(420): error C2661: 'v8::Value::ToString': no overloaded function takes 0 arguments [d:\tmp\zzz\robotjs\build\ro botjs.vcxproj]
..\src\robotjs.cc(420): error C2512: 'v8::String::Utf8Value::Utf8Value': no appropriate default constructor available [d:\tmp\zzz \robotjs\build\robotjs.vcxproj]
..\src\robotjs.cc(434): warning C4996: 'v8::Object::Get': was declared deprecated [d:\tmp\zzz\robotjs\build\robotjs.vcxproj]
  c:\users\der2\.node-gyp\12.1.0\include\node\v8.h(3416): note: see declaration of 'v8::Object::Get'
..\src\robotjs.cc(457): error C2661: 'v8::Value::ToString': no overloaded function takes 0 arguments [d:\tmp\zzz\robotjs\build\ro botjs.vcxproj]
..\src\robotjs.cc(457): error C2512: 'v8::String::Utf8Value::Utf8Value': no appropriate default constructor available [d:\tmp\zzz \robotjs\build\robotjs.vcxproj]
..\src\robotjs.cc(589): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(603): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(639): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(640): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(708): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(709): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(710): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(711): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(768): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robot js.vcxproj]
..\src\robotjs.cc(769): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robot js.vcxproj]
..\src\robotjs.cc(770): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robot js.vcxproj]
..\src\robotjs.cc(771): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robot js.vcxproj]
..\src\robotjs.cc(772): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robot js.vcxproj]
..\src\robotjs.cc(774): warning C4996: 'v8::Object::Get': was declared deprecated [d:\tmp\zzz\robotjs\build\robotjs.vcxproj]
  c:\users\der2\.node-gyp\12.1.0\include\node\v8.h(3412): note: see declaration of 'v8::Object::Get'
..\src\robotjs.cc(788): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
..\src\robotjs.cc(789): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [d:\tmp\zzz\robotjs\build\robotj s.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (d:\tmp\zzz\robotjs\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\nodejs\\node.exe" "d:\\tmp\\zzz\\robotjs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\tmp\zzz\robotjs
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok
```

**Comment by just-push-it** [comment]
I'm receiving the same error output when trying to build for Electron 5.0.0

Node: 12.1.0
Robotjs: 0.5.1

**Comment by emko** [comment]
anyone figured out how to fix this?

**Comment by just-push-it** [comment]
> anyone figured out how to fix this?

I **believe** this is caused by previously depreciated functions being removed from the version of v8 that Node12 uses. Basically they'll need to update robotjs.cc in order to fix this. In the mean time, Node11 should still work.

**Comment by emko** [comment]
> 
> 
> > anyone figured out how to fix this?
> 
> I **believe** this is caused by previously depreciated functions being removed from the version of v8 that Node12 uses. Basically they'll need to update robotjs.cc in order to fix this. In the mean time, Node11 should still work.

but doesn't electron 5 need node 12? or will it still work with 11?

**Comment by just-push-it** [comment]
> but doesn't electron 5 need node 12? or will it still work with 11?

Correct, you'd have to use Electron 4.2.0

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.

**Comment by liketurbo** [comment]
1. Please use `nvm` and switch to the version `node@8`
2. Complete installation of all prerequisites from [node-gyp](https://github.com/nodejs/node-gyp)

**Comment by octalmage** [comment]
Closing stale issues as part of a cleanup. If this is still an issue, please reopen and I'll take a look. Thanks!
