### ISSUE TITLE
Failed at the robotjs@0.5.1 install script.

### ISSUE THREAD

**Issue by Slyke** [octalmage/robotjs#481]
Can't install robotjs

## Expected Behavior
Install robotjs

## Current Behavior
Getting install errors after running `npm install`

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)
Run `npm install robotjs`

## Context
Unusable in current state.

## Your Environment

* RobotJS version: Latest one
* Node.js version: v10.14.2
* npm version: 6.4.1
* Operating System: Windows 10

Log file:
```
1685 verbose stack Error: robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
1685 verbose stack Exit status 1
1685 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
1685 verbose stack     at EventEmitter.emit (events.js:182:13)
1685 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1685 verbose stack     at ChildProcess.emit (events.js:182:13)
1685 verbose stack     at maybeClose (internal/child_process.js:962:16)
1685 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
1686 verbose pkgid robotjs@0.5.1
1687 verbose cwd C:\Users\Slyke\Desktop\vitalcopy
1688 verbose Windows_NT 10.0.17763
1689 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "robotjs"
1690 verbose node v10.14.2
1691 verbose npm  v6.4.1
1692 error code ELIFECYCLE
1693 error errno 1
1694 error robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
1694 error Exit status 1
1695 error Failed at the robotjs@0.5.1 install script.
1695 error This is probably not a problem with npm. There is likely additional logging output above.
1696 verbose exit [ 1, true ]

```

**Comment by Slyke** [comment]
Also tried with node version 8.16.0 and same result.

**Comment by aeonixlegit** [comment]
Try to use node v59 versions (9.0.0-9.11.2).

**Comment by oktapodia** [comment]
A new version of robotjs supporting the latest NodeJS version will be published soon.

**Comment by liketurbo** [comment]
1. Please use `nvm` and switch to the version `node@8`
2. Complete installation of all prerequisites from [node-gyp](https://github.com/nodejs/node-gyp)

**Comment by octalmage** [comment]
Closing stale issues as part of a cleanup. If this is still an issue, please reopen and I'll take a look. Thanks!
