### ISSUE TITLE
Not compatible with Node.js 10.15.3?

### ISSUE THREAD

**Issue by HaleyWang** [octalmage/robotjs#485]
Can't install robotjs

## Expected Behavior

Install robotjs

## Current Behavior

Getting install errors after running npm install

## Possible Solution

Not sure.

## Steps to Reproduce (for bugs)

1.npm i robotjs

## Context

Uncaught Exception:
Error: The module '/Users/haley/Documents/w/demo/electron-quick-start/node_modules/robotjs/build/Release/robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:850:18)
    at Object.func [as .node] (electron/js2c/asar.js:155:31)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/haley/Documents/w/demo/electron-quick-start/node_modules/robotjs/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:808:30)

## Your Environment

* RobotJS version:     "^0.5.1"
* Node.js version: v10.15.3
* npm version:6.4.1
* Operating System:macOS 10.13.6 (17G65)

**Comment by shravan999** [comment]
Hi @HaleyWang same issue here, any update on this?

- RobotJS version: "^0.5.1"

- Node.js version: v10.15.3

- npm version: 6.4.1

- OS: Windows 7

**Comment by VyhrystMax** [comment]
![Снимок экрана 2019-09-17 в 13 50 12](https://user-images.githubusercontent.com/16073132/65035574-2f8fa700-d952-11e9-9e36-8a9e1b9ca3cf.png)

Same issue. Is there any solution for this?

**Comment by AJDownie** [comment]
I doubt it will ever get accepted but use this: octalmage/robotjs#489

**Comment by oktapodia** [comment]
A new version of robotjs supporting the latest NodeJS version will be published soon.

**Comment by liketurbo** [comment]
1. Please use `nvm` and switch to the version `node@8`
2. Complete installation of all prerequisites from [node-gyp](https://github.com/nodejs/node-gyp)

**Comment by octalmage** [comment]
Closing stale issues as part of a cleanup. If this is still an issue, please reopen and I'll take a look. Thanks!
