### ISSUE TITLE
Doesn't install in Electron project

### ISSUE THREAD

**Issue by PCMACHero** [octalmage/robotjs#506]
## Expected Behavior
Tried npm rebuild --runtime=electron --target=6.0.5 --disturl=https://atom.io/download/atom-shell --abi=73

## Current Behavior
This is the error log:

`> core-js@2.6.9 postinstall /Users/dev1/dev/elecbp/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> electron@6.0.5 postinstall /Users/dev1/dev/elecbp/node_modules/electron
> node install.js

> fsevents@1.2.9 install /Users/dev1/dev/elecbp/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/dev1/dev/elecbp/node_modules/fsevents/lib/binding/Release/electron-v6.0-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> iohook@0.6.1 install /Users/dev1/dev/elecbp/node_modules/iohook
> node install.js

Can't resolve main package.json file
Downloading prebuild for platform: iohook-v0.6.1-node-v64-darwin-x64
Downloading prebuild.tar.gz
[============================================>] 100.0% of 25.52 kB (25.52 kB/s)

> robotjs@0.5.1 install /Users/dev1/dev/elecbp/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=6.0.5 runtime=electron arch=x64 platform=darwin)
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
../src/robotjs.cc:63:28: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        const size_t x = info[0]->Int32Value();
                                  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:64:28: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        const size_t y = info[1]->Int32Value();
                                  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:97:22: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        size_t x = info[0]->Int32Value();
                            ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:98:22: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        size_t y = info[1]->Int32Value();
                            ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:114:22: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        size_t x = info[0]->Int32Value();
                            ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:115:22: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        size_t y = info[1]->Int32Value();
                            ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:143:39: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
                v8::String::Utf8Value bstr(info[0]->ToString());
                                                    ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2520:10: note: 'ToString' has
      been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:143:25: warning: 'Utf8Value' is deprecated: Use Isolate
      version [-Wdeprecated-declarations]
                v8::String::Utf8Value bstr(info[0]->ToString());
                                      ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2964:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:159:22: warning: 'BooleanValue' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
                doubleC = info[1]->BooleanValue();
                                   ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2541:3: note: 'BooleanValue' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:239:24: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        mouseDelay = info[0]->Int32Value();
                              ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:251:19: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        int x = info[0]->Int32Value();
                         ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:252:19: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        int y = info[1]->Int32Value();
                         ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:418:44: error: expected '(' for function-style cast or type
      construction
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                  ~~~~~~~~~^
../src/robotjs.cc:418:28: error: no member named 'Handle' in namespace 'v8'
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                       ~~~~^
../src/robotjs.cc:418:46: error: use of undeclared identifier 'value'; did you
      mean 'False'?
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                             ^~~~~
                                             False
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:303:25: note: 'False' declared
      here
  friend Local<Boolean> False(Isolate* isolate);
                        ^
../src/robotjs.cc:418:53: error: unexpected type name 'MMKeyFlags': expected
      expression
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                    ^
../src/robotjs.cc:418:65: error: use of undeclared identifier 'flags'
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                                ^
../src/robotjs.cc:418:71: error: expected ';' after top level declarator
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                                      ^
                                                                      ;
../src/robotjs.cc:762:1: error: unknown type name 'BMP'
BMP buildBMP(Local<Object> info)
^
../src/robotjs.cc:766:2: error: unknown type name 'BMP'
        BMP img;
        ^
../src/robotjs.cc:768:19: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        img.width = obj->Get(Nan::New("width").ToLocalChecked())->Uint32Value();
                         ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:3384:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:768:60: warning: 'Uint32Value' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        img.width = obj->Get(Nan::New("width").ToLocalChecked())->Uint32Value();
                                                                  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2544:3: note: 'Uint32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:769:20: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        img.height = obj->Get(Nan::New("height").ToLocalChecked())->Uint...
                          ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:3384:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:769:62: warning: 'Uint32Value' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        img.height = obj->Get(Nan::New("height").ToLocalChecked())->Uint...
                                                                    ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2544:3: note: 'Uint32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:770:23: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        img.byteWidth = obj->Get(Nan::New("byteWidth").ToLocalChecked())...
                             ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:3384:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:770:68: warning: 'Uint32Value' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        img.byteWidth = obj->Get(Nan::New("byteWidth").ToLocalChecked())->Uint32...
                                                                          ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2544:3: note: 'Uint32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:771:26: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        img.bitsPerPixel = obj->Get(Nan::New("bitsPerPixel").ToLocalChec...
                                ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:3384:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:771:74: warning: 'Uint32Value' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
  ...= obj->Get(Nan::New("bitsPerPixel").ToLocalChecked())->Uint32Value();
                                                            ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2544:3: note: 'Uint32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:772:27: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        img.bytesPerPixel = obj->Get(Nan::New("bytesPerPixel").ToLocalCh...
                                 ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:3384:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:772:76: warning: 'Uint32Value' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
  ...= obj->Get(Nan::New("bytesPerPixel").ToLocalChecked())->Uint32Value();
                                                             ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2544:3: note: 'Uint32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:774:38: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        char* buf = node::Buffer::Data(obj->Get(Nan::New("image").ToLoca...
                                            ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:3384:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:788:22: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        size_t x = info[1]->Int32Value();
                            ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:789:22: warning: 'Int32Value' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        size_t y = info[2]->Int32Value();
                            ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8.h:2545:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dev1/.node-gyp/6.0.5/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/robotjs.cc:792:2: error: unknown type name 'BMP'
        BMP img = buildBMP(Nan::To<v8::Object>(info[0]).ToLocalChecked());
        ^
../src/robotjs.cc:807:2: error: use of undeclared identifier 'padHex'
        padHex(color, hex);
        ^
../src/robotjs.cc:842:47: error: use of undeclared identifier 'keyTap'; did you
      mean 'keyUp'?
                Nan::GetFunction(Nan::New<FunctionTemplate>(keyTap)).ToL...
                                                            ^~~~~~
                                                            keyUp
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/Events.h:41:3: note: 
      'keyUp' declared here
  keyUp                         = 4,
  ^
../src/robotjs.cc:845:47: error: use of undeclared identifier 'keyToggle'; did
      you mean 'doToggle'?
                Nan::GetFunction(Nan::New<FunctionTemplate>(keyToggle))....
                                                            ^~~~~~~~~
                                                            doToggle
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/TextEdit.h:280:3: note: 
      'doToggle' declared here
  doToggle                      = 32    /*toggle mode for TESetStyle*/
  ^
../src/robotjs.cc:854:47: error: use of undeclared identifier
      'setKeyboardDelay'; did you mean 'keyboardDelay'?
  ...Nan::GetFunction(Nan::New<FunctionTemplate>(setKeyboardDelay)).ToLocalCh...
                                                 ^~~~~~~~~~~~~~~~
                                                 keyboardDelay
../src/robotjs.cc:21:5: note: 'keyboardDelay' declared here
int keyboardDelay = 10;
    ^
../src/robotjs.cc:857:47: error: use of undeclared identifier 'getPixelColor'
                Nan::GetFunction(Nan::New<FunctionTemplate>(getPixelColo...
                                                            ^
../src/robotjs.cc:860:47: error: use of undeclared identifier 'getScreenSize'
                Nan::GetFunction(Nan::New<FunctionTemplate>(getScreenSiz...
                                                            ^
../src/robotjs.cc:863:47: error: use of undeclared identifier 'captureScreen'
                Nan::GetFunction(Nan::New<FunctionTemplate>(captureScree...
                                                            ^
../src/robotjs.cc:869:47: error: use of undeclared identifier 'getXDisplayName'
                Nan::GetFunction(Nan::New<FunctionTemplate>(getXDisplayN...
                                                            ^
../src/robotjs.cc:872:47: error: use of undeclared identifier 'setXDisplayName'
                Nan::GetFunction(Nan::New<FunctionTemplate>(setXDisplayN...
                                                            ^
In file included from ../src/robotjs.cc:2:
In file included from ../../nan/nan.h:288:
../../nan/nan_new.h:208:31: error: cannot initialize a parameter of type
      'Nan::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type '(anonymous
      enum at
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/Events.h:36:1)'
  return imp::Factory<T>::New(arg0);
                              ^~~~
../src/robotjs.cc:842:25: note: in instantiation of function template
      specialization 'Nan::New<v8::FunctionTemplate, (anonymous enum at
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/Events.h:36:1)>'
      requested here
                Nan::GetFunction(Nan::New<FunctionTemplate>(keyTap)).ToL...
                                      ^
../../nan/nan_implementation_12_inl.h:119:54: note: passing argument to
      parameter 'callback' here
Factory<v8::FunctionTemplate>::New( FunctionCallback callback
                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
25 warnings and 20 errors generated.
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dev1/dev/elecbp/node_modules/robotjs
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dev1/.npm/_logs/2019-09-19T01_37_27_723Z-debug.log`

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change. -->

## Steps to Reproduce (for bugs)

1. npm install robotjs
2. npm install -g node-gyp
3. npm rebuild --runtime=electron --target=6.0.5 --disturl=https://atom.io/download/atom-shell --abi=73
4. profit


## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in. -->
* RobotJS version: 0.5.1
* Node.js version: v10.16.3
* npm version: 6.9.0
* Operating System: Mojave 10.14.6
*Electron version: 6.0.5

**Comment by Mkalo** [comment]
Try running `npm update nan` before rebuild

**Comment by Impulse87** [comment]
You can get it to work with electron-rebuild with script in package.json like `"postinstall": "electron-rebuild -f -w robotjs"` and you need to go back to electron version 4.2.10, since electorn-rebuild and underlying node-gyp doesn't work with Electron v5+ as of now (currently latest Electron version is 6.0.10).

**Comment by PCMACHero** [comment]
> You can get it to work with npm package `electron-rebuild`. Put the script `"postinstall": "electron-rebuild -f -w robotjs"` into your package.json and you need to go back to electron version 4.2.10, since electorn-rebuild and underlying node-gyp doesn't work with Electron v5+ as of now (currently latest Electron version is 6.0.10). This additional infos could also be helpfull -> https://spin.atomicobject.com/2019/03/27/node-gyp-windows/

Will try, and report results.

**Comment by PCMACHero** [comment]
> You can get it to work with npm package `electron-rebuild`. Put the script `"postinstall": "electron-rebuild -f -w robotjs"` into your package.json and you need to go back to electron version 4.2.10, since electorn-rebuild and underlying node-gyp doesn't work with Electron v5+ as of now (currently latest Electron version is 6.0.10). This additional infos could also be helpfull -> https://spin.atomicobject.com/2019/03/27/node-gyp-windows/

Great, this managed to install, and it works. The only issue now is that robojs can only be used inside my main.js electron file, and not in my other js files where it would actually need it to work. Any ideas?

**Comment by Toinane** [comment]
> > You can get it to work with npm package `electron-rebuild`. Put the script `"postinstall": "electron-rebuild -f -w robotjs"` into your package.json and you need to go back to electron version 4.2.10, since electorn-rebuild and underlying node-gyp doesn't work with Electron v5+ as of now (currently latest Electron version is 6.0.10). This additional infos could also be helpfull -> https://spin.atomicobject.com/2019/03/27/node-gyp-windows/
> 
> Great, this managed to install, and it works. The only issue now is that robojs can only be used inside my main.js electron file, and not in my other js files where it would actually need it to work. Any ideas?
> 
> Update: Im using remote now, and it works. I dont know if this is the solution, or if its just a bandaid.

RobotJS can be only used in the main process and not renderer process. You have to use the IPC process to transmit informations between main and renderer. Remote is an alternative but I don't recommend this solution.

**Comment by dsteinman** [comment]
Electron 7.1.2 is working with this branch https://github.com/octalmage/robotjs/tree/fix/node13

**Comment by oktapodia** [comment]
A new version of robotjs supporting the latest NodeJS version will be published soon.

**Comment by liketurbo** [comment]
1. Please use `nvm` and switch to the version `node@8`
2. Complete installation of all prerequisites from [node-gyp](https://github.com/nodejs/node-gyp)

**Comment by octalmage** [comment]
Closing stale issues as part of a cleanup. If this is still an issue, please reopen and I'll take a look. Thanks!
