### ISSUE TITLE
getMousePos returns x: 0, y: 0 no matter what on Mac OS X Catalina

### ISSUE THREAD

**Issue by brandonros** [octalmage/robotjs#548]
```
 "robotjs": {
      "version": "0.6.0",
      "resolved": "https://registry.npmjs.org/robotjs/-/robotjs-0.6.0.tgz",
      "integrity": "sha512-6pRWI3d+CBZqCXT/rsJfabbZoELua+jTeXilG27F8Jvix/J2BYZ0O7Tly2WCmXyqw5xYdCvOwvCeLRHEtXkt4w==",
      "requires": {
        "nan": "^2.14.0",
        "node-abi": "^2.13.0",
        "prebuild-install": "^5.3.3"
      }
    },
```

```
const robot = require('robotjs')
console.log(robot.getMousePos())`
> { x: 0, y: 0 }
```

**Comment by brandonros** [comment]
```
$ ../node_modules/.bin/jasmine mouse.js 
Started
.FF....

Failures:
1) Mouse Move the mouse.
  Message:
    Expected false to be truthy.
  Stack:
    Error: Expected false to be truthy.
        at UserContext.<anonymous> (/Users/brandonros/Desktop/bilge-bot/robotjs/test/mouse.js:20:34)
  Message:
    Expected false to be truthy.
  Stack:
    Error: Expected false to be truthy.
        at UserContext.<anonymous> (/Users/brandonros/Desktop/bilge-bot/robotjs/test/mouse.js:21:34)

2) Mouse Move the mouse smoothly.
  Message:
    Expected 0 to equal 100.
  Stack:
    Error: Expected 0 to equal 100.
        at UserContext.<anonymous> (/Users/brandonros/Desktop/bilge-bot/robotjs/test/mouse.js:42:26)
  Message:
    Expected 0 to equal 100.
  Stack:
    Error: Expected 0 to equal 100.
        at UserContext.<anonymous> (/Users/brandonros/Desktop/bilge-bot/robotjs/test/mouse.js:43:26)

7 specs, 2 failures
Finished in 2.199 seconds
```

**Comment by brandonros** [comment]
![image](https://user-images.githubusercontent.com/8949910/74304398-e25e0880-4d2a-11ea-8666-bf3b9ec900a1.png)

**Comment by oktapodia** [comment]
The new robotjs version has been published but there is a bug into the NodeJS core about the screen sizing, it should be packaged soon into a new NodeJS version https://github.com/libuv/libuv/issues/2566

**Comment by zkcrescent** [comment]
+1

**Comment by fabiomcosta** [comment]
yep, this seems to work properly on Node 14.1.0 (and probably earlier as well, but that's the one I just tried)

**Comment by oktapodia** [comment]
Thank you for letting us know @fabiomcosta, I can now close it

**Comment by brandonros** [comment]
```
$ npm install

> robotjs@0.5.1 install /Users/bros/vpn/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.18.2 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
../src/robotjs.cc:63:39: error: too few arguments to function call, single
      argument 'context' was not specified
        const size_t x = info[0]->Int32Value();
                         ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:64:39: error: too few arguments to function call, single
      argument 'context' was not specified
        const size_t y = info[1]->Int32Value();
                         ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:97:33: error: too few arguments to function call, single
      argument 'context' was not specified
        size_t x = info[0]->Int32Value();
                   ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:98:33: error: too few arguments to function call, single
      argument 'context' was not specified
        size_t y = info[1]->Int32Value();
                   ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:114:33: error: too few arguments to function call, single
      argument 'context' was not specified
        size_t x = info[0]->Int32Value();
                   ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:115:33: error: too few arguments to function call, single
      argument 'context' was not specified
        size_t y = info[1]->Int32Value();
                   ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:143:39: error: no matching member function for call to
      'ToString'
                v8::String::Utf8Value bstr(info[0]->ToString());
                                           ~~~~~~~~~^~~~~~~~
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2668:44: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2684:31: note: 
      candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
../src/robotjs.cc:159:22: error: no matching member function for call to
      'BooleanValue'
                doubleC = info[1]->BooleanValue();
                          ~~~~~~~~~^~~~~~~~~~~~
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2699:8: note: 
      candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2702:51: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../src/robotjs.cc:239:35: error: too few arguments to function call, single
      argument 'context' was not specified
        mouseDelay = info[0]->Int32Value();
                     ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:251:30: error: too few arguments to function call, single
      argument 'context' was not specified
        int x = info[0]->Int32Value();
                ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:252:30: error: too few arguments to function call, single
      argument 'context' was not specified
        int y = info[1]->Int32Value();
                ~~~~~~~~~~~~~~~~~~~ ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:2709:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:368:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:418:44: error: expected '(' for function-style cast or type
      construction
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                  ~~~~~~~~~^
../src/robotjs.cc:418:28: error: no member named 'Handle' in namespace 'v8'
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                       ~~~~^
../src/robotjs.cc:418:46: error: use of undeclared identifier 'value'; did you
      mean 'False'?
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                             ^~~~~
                                             False
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:307:25: note: 
      'False' declared here
  friend Local<Boolean> False(Isolate* isolate);
                        ^
../src/robotjs.cc:418:53: error: unexpected type name 'MMKeyFlags': expected
      expression
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                    ^
../src/robotjs.cc:418:65: error: use of undeclared identifier 'flags'
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                                ^
../src/robotjs.cc:418:71: error: expected ';' after top level declarator
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                                      ^
                                                                      ;
../src/robotjs.cc:762:1: error: unknown type name 'BMP'
BMP buildBMP(Local<Object> info)
^
../src/robotjs.cc:766:2: error: unknown type name 'BMP'
        BMP img;
        ^
../src/robotjs.cc:768:19: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        img.width = obj->Get(Nan::New("width").ToLocalChecked())->Uint32Value();
                         ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8.h:3553:3: note: 
      'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/bros/Library/Caches/node-gyp/12.18.2/include/node/v8config.h:328:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.

```

Whole slew of errors trying to pull in the latest libuv changes in node.js v12.18.2
