### ISSUE TITLE
Create Windows Installer. 

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#57]
It would be awesome to have an easy Windows installer that installs all of the dependices, including Node.js if needed. This would let people that are just interested in the automation use RobotJS. 

I want this project to be as accessible as AutoHotkey.

**Comment by Deltatiger** [comment]
It would be better to have an installer for windows than npm I guess. Especially after seeing the various installation bugs that are coming up (Not everyone prefers VS for development so they may not have it).

**Comment by octalmage** [comment]
Yeah having users install Visual Studio just to use your module is pretty insane. Some modules use node-pre-gyp for this, and I think I want to do it also. This way users can download pre-built binaries for at least Windows. I'll create a new issue to look into this.

**Comment by octalmage** [comment]
Having pre-built binaries will help, but I'd still like an installer to make the process really easy. I'd like it to have the option to add Node.js to the right click->new menu with the default script requiring the global RobotJS package. It could even install EncloseJS or nexe to allow users to easily compile their apps. 

This is very similar to how AutoHotkey does things.

**Comment by Deltatiger** [comment]
It all got fussy for me in the last post. We need more deliberation. First we would have to list out how we want to install it. Its better to provide both the binaries and the compilation process because I dont know what will go wrong in windows. If binaries dont work then the same installer will move on to a compilation of the code after installing all the required stuff. Just as a fail safe.

**Comment by hortinstein** [comment]
In addition to the installer route, will you be pursuing dependency  bundling?  I am trying to figure out how to eventually bundle this into a [electron app](https://github.com/atom/electron)

**Comment by octalmage** [comment]
For an electron app you would just need to copy the node_modules folder.

**Comment by hortinstein** [comment]
right, but would anyone using it still need to have visual studio installed (for windows)?

**Comment by octalmage** [comment]
Nope! That's only needed for compiling RobotJS. Once it's compiled the binary (robotjs.node) can be distributed without the dependencies.

**Comment by hortinstein** [comment]
awesome!  Thank you for the quick response!  I will let you know if I ever get this project off the ground and maybe you can put it on your [projects page](https://github.com/octalmage/robotjs/wiki/Projects-using-RobotJS).  I have been toying with this idea forever and robotjs (along with a few other key libraries) solves huge barriers of entry that were keeping me from pursuing it.

**Comment by octalmage** [comment]
No problem! And keep me updated. I'd love to see what you're making.

**Comment by dkrutsko** [comment]
I'm currently experimenting with shipping pre-built binaries through NPM. So far the tests have been positive, so positive in fact that I don't see a reason to use node-gyp or node-pre-gyp anymore. And frankly I don't see a reason for an installer, you should be able to install robotjs like any other package through npm and have it work on the target platform without any compilation steps or any dependencies of any kind. I don't understand the need to overburden yourself with all this extra work.

**Comment by octalmage** [comment]
Did you read my comments above? With an installer you have more control, that's something I need. 

Using node-pre-gyp is the preferred way to distribute binaries. It falls back to building, and that's important to me.

**Comment by dkrutsko** [comment]
More control for what? perhaps I'm misunderstanding what the goals are. Also, you don't need that many binaries to support a large number of platforms. With just 6 binaries you're able to support about 90% of the operating systems out there assuming you're targeting node 0.12. And another 6 for 0.10. And node-pre-gyp probably won't help because if the user has to compile the binary themselves, it will probably fail because the platform is incompatible, I'm of course talking about Linux here. OS X and Windows will have full support (I'm still testing OS X, will report once I know for sure).

**Comment by octalmage** [comment]
I want a one click installer for new users, users without Node.js or npm. I also want to add RobotJS to the right click->new menu, and have the default script require a globally installed RobotJS package. The goal is to replace AutoHotkey and this would make the experience very similar.

**Comment by octalmage** [comment]
It's just an idea, not sure if I'm going to do it but installers are easy to make.

**Comment by dkrutsko** [comment]
Okay well, let's for a second say that node.js isn't already a one click install and installing robotjs globally doesn't get the job done. The idea here is to package a node executable, along with the prebuilt binaries and the robotjs library. You're going to need a lot more features if you plan to replace AutoHotkey. For instance, you'll probably need to include other support libraries which may or may not have native addons. Maybe you'll want to ship an editor as well with some `double click to execute` action?

My point is that it's already trivial to use and install node and other libraries, if you're making an installer you will have to ask yourself whether you'll be installing node as well (at which point why not just install node and robotjs normally). If you're not installing node then you're missing out on all the simplicity of npm which means preinstalling a bunch of libraries which the user may or may not need.

I'm just brainstorming here btw :-D

**Comment by dkrutsko** [comment]
Also good news, I just found out that you can upload node files to NPM directly. I always thought they disallowed that which is why everybody was using a CDN. But apparently it works, my only question is why haven't I come across anybody doing this before. Am I missing something? Assuming a library is targeting Node 0.12.x for windows, why not just store the addon on NPM?

**Comment by octalmage** [comment]
Using node-pre-gyp lets you easily automate the build process using TravisCI and AppVeyor. I think bumping the project version and publishing to npm isn't as clean.

**Comment by dkrutsko** [comment]
It's not as clean but it gives you the most control over your build environment. For instance I have 12 VM's setup specifically to test and deploy my project with tightly controlled build configurations to ensure that it'll work on the largest number of systems. Although TravisCI and AppVeyor may make things easier, it disconnects us from what is arguably the most important step in the process. Also, with a project like robotjs, writing fully automated test cases is not possible which makes CI tools useless.

**Comment by shubhamsaxena123** [comment]
Hi,
I am trying to use Robotjs which executes "node-gyp rebuild" in the script. But unfortunately it does not work for Ubuntu 14.04. Then I tried in Windows 8 and used your "node-pre-gyp" but its still not working. I am attaching the screenshot for the logs of the "node-gyp rebuild" command in cmd(Windows).

Thanks for the support. :)

![node-gyprebuild](https://cloud.githubusercontent.com/assets/8664643/9630012/1701100a-512c-11e5-9e78-c00abe2d7829.png)

**Comment by vshymanskyy** [comment]
I would like to vote for this feature.
Installing on windows should be "single click". This will significantly boost usage of the module.

**Comment by octalmage** [comment]
Agreed! I've got some ideas for how to set this up.

**Comment by hortinstein** [comment]
cant wait to see, this will make it much easier for me to proceed with my use case.  Thanks!

**Comment by blak3r2** [comment]
Hey guys,

I've read this thread and a couple others and what i've gathered is for windows support it still requires all the dependencies to be installed and it's built using node-gyp.

I managed to get it built on a dev box I have which was windows server 2008R2.  But, the binaries didn't work on a winxp or a windows 10 box (I got the error below).  Probably need to have some redistributable installed i gather. 

I'm just trying to get it working on a single windows 10 instance and it's been challenging trying to walk the end-user through the install. 

@dkrutsko do you have pre built binaries anywhere you could post?


```
C:\package>node app.js
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
\\?\C:\package\node_modules\robotjs\build\Release\robotjs.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\package\node_modules\robotjs\index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by octalmage** [comment]
Hey @blak3r2! Would you mind opening a new issue? This issue is for tracking progress on the Windows installer. Thanks!

**Comment by octalmage** [comment]
The error you got happens when the module was compiled for a 64bit architecture, but is ran on 32bit. There's more detailed instructions for Windows [here](https://github.com/nodejs/node-gyp#installation). 

I don't believe a binary has to be compiled on the same version of Windows, but it'd believe it since different dev tools are used.

**Comment by octalmage** [comment]
Closing stale issues as part of a cleanup. If this is still an issue, please reopen and I'll take a look. Thanks!
