### ISSUE TITLE
npm install robotjs not working

### ISSUE THREAD

**Issue by Androiderr** [octalmage/robotjs#590]
I am trying to install robotjs. For that purpose, I have nodeJS on Visual Studio Code. This the error i get.

> robotjs@0.6.0 install C:\Users\awais\Documents\ScrapperProjects\Twitter Bot\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.14.1 runtime=node arch=x64 libc= platform=win32)

C:\Users\awais\Documents\ScrapperProjects\Twitter Bot\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config        
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt      
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\awais\Documents\ScrapperProjects\Twitter Bot\node_modules\robotjs
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\awais\Documents\ScrapperProjects\Twitter Bot\package.json'
npm WARN Twitter Bot No description
npm WARN Twitter Bot No repository field.
npm WARN Twitter Bot No README data
npm WARN Twitter Bot No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
PS C:\Users\awais\Documents\ScrapperProjects\Twitter Bot> npm install robotjs

> robotjs@0.6.0 install C:\Users\awais\Documents\ScrapperProjects\Twitter Bot\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.14.1 runtime=node arch=x64 libc= platform=win32)

C:\Users\awais\Documents\ScrapperProjects\Twitter Bot\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt        
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer  
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\awais\Documents\ScrapperProjects\Twitter Bot\node_modules\robotjs
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\awais\Documents\ScrapperProjects\Twitter Bot\package.json'
npm WARN Twitter Bot No description
npm WARN Twitter Bot No repository field.
npm WARN Twitter Bot No README data
npm WARN Twitter Bot No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Offpics** [comment]
Did you follow **Building** section in the README?

**Comment by Sergey-Churilin** [comment]
I observe the same problem with Electron10. When modules are installed, electron-builder rebuild them and the process failed. Issue can be reproduced with my sample https://github.com/Sergey-Churilin/Electron-samples/tree/electron10-robotjs

**Comment by Tymski** [comment]
> Did you follow **Building** section in the README?

Using the building section doesn't help at all, the build tools install, but you can't install robotjs

**Comment by Draginfable** [comment]
What finally worked for me was using the VS Build tools 2017 and having the same node version as the one that electron uses internally.

**Comment by Ruvik22** [comment]
Please ensure you have the required dependencies before installing:

Windows

- windows-build-tools npm package (npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe)

Mac

- Xcode Command Line Tools.

Linux

- Python (v2.7 recommended, v3.x.x is not supported).

- make.

- A C/C++ compiler like GCC.

- libxtst-dev and libpng++-dev (sudo apt-get install libxtst-dev libpng++-dev).

Install node-gyp using npm:
`npm install -g node-gyp`

Then build:
`node-gyp rebuild`

**Comment by msynk** [comment]
native node modules (like robotjs) need a build process after install which is done with node-gyp.
the node-gyp toolset itself requires some other prerequisites in order to run. this is what is required for windows:

* [Python](https://www.python.org/)
* Microsoft Visual C++ Redistributable for Visual Studio

I think recent versions of nodejs installer for windows include the C++ redistributable. but you need to install Python separately as described in the error logs you've posted.

**Comment by octalmage** [comment]
Closing stale issues as part of a cleanup. If this is still an issue, please reopen and I'll take a look. Thanks!
