### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by PinocchioStrings** [octalmage/robotjs#680]

**Comment by PinocchioStrings** [comment]
I found the binaries here:
https://github.com/octalmage/robotjs/releases

Maybe someone could point me to how I can install it manually as a node module?

**Comment by PinocchioStrings** [comment]
UPDATE:

For some reason NPM responds differently now. I didn't change anything, just tried again (this time with "npm i robotjs" as was mentioned on npmjs.com).

It still doesn't work, though. Now I'm getting errors about python and something called node-gyp for some reason.

This from the debug log:

481 verbose stack Error: command failed
481 verbose stack     at ChildProcess.<anonymous> (D:\NodeJS\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:63:27)
481 verbose stack     at ChildProcess.emit (node:events:327:20)
481 verbose stack     at maybeClose (node:internal/child_process:1048:16)
481 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
482 verbose pkgid robotjs@0.6.0
483 verbose cwd C:\Users\Murmandamus
484 verbose Windows_NT 10.0.19042
485 verbose argv "D:\\NodeJS\\node.exe" "D:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "i" "robotjs"
486 verbose node v15.0.1
487 verbose npm  v7.0.3
488 error code 1
489 error path C:\Users\Murmandamus\node_modules\robotjs
490 error command failed
491 error command C:\WINDOWS\system32\cmd.exe /d /s /c "prebuild-install || node-gyp rebuild"
492 error gyp info it worked if it ends with ok
492 error gyp info using node-gyp@7.1.2
492 error gyp info using node@15.0.1 | win32 | x64
492 error gyp ERR! find Python
492 error gyp ERR! find Python Python is not set from command line or npm configuration
492 error gyp ERR! find Python Python is not set from environment variable PYTHON
492 error gyp ERR! find Python checking if "python3" can be used
492 error gyp ERR! find Python - "python3" is not in PATH or produced an error
492 error gyp ERR! find Python checking if "python" can be used
492 error gyp ERR! find Python - "python" is not in PATH or produced an error
492 error gyp ERR! find Python checking if "python2" can be used
492 error gyp ERR! find Python - "python2" is not in PATH or produced an error
492 error gyp ERR! find Python checking if Python is C:\Python37\python.exe
492 error gyp ERR! find Python - "C:\Python37\python.exe" could not be run
492 error gyp ERR! find Python checking if Python is C:\Python27\python.exe
492 error gyp ERR! find Python - "C:\Python27\python.exe" could not be run
492 error gyp ERR! find Python checking if the py launcher can be used to find Python
492 error gyp ERR! find Python - "py.exe" is not in PATH or produced an error
492 error gyp ERR! find Python
492 error gyp ERR! find Python **********************************************************
492 error gyp ERR! find Python You need to install the latest version of Python.
492 error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
492 error gyp ERR! find Python you can try one of the following options:
492 error gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
492 error gyp ERR! find Python   (accepted by both node-gyp and npm)
492 error gyp ERR! find Python - Set the environment variable PYTHON
492 error gyp ERR! find Python - Set the npm configuration variable python:
492 error gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
492 error gyp ERR! find Python For more information consult the documentation at:
492 error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
492 error gyp ERR! find Python **********************************************************
492 error gyp ERR! find Python
492 error gyp ERR! configure error
492 error gyp ERR! stack Error: Could not find any Python installation to use
492 error gyp ERR! stack     at PythonFinder.fail (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\find-python.js:302:47)
492 error gyp ERR! stack     at PythonFinder.runChecks (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
492 error gyp ERR! stack     at PythonFinder.<anonymous> (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\find-python.js:200:18)
492 error gyp ERR! stack     at PythonFinder.execFileCallback (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\find-python.js:266:16)
492 error gyp ERR! stack     at exithandler (node:child_process:316:5)
492 error gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:328:5)
492 error gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
492 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:275:12)
492 error gyp ERR! stack     at onErrorNT (node:internal/child_process:465:16)
492 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:80:21)
492 error gyp ERR! System Windows_NT 10.0.19042
492 error gyp ERR! command "D:\\NodeJS\\node.exe" "D:\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
492 error gyp ERR! cwd C:\Users\Murmandamus\node_modules\robotjs
492 error gyp ERR! node -v v15.0.1
492 error gyp ERR! node-gyp -v v7.1.2
492 error gyp ERR! not ok
493 verbose exit 1

**Comment by PinocchioStrings** [comment]
Suddenly I have a node_modules folder in my user folder on C:, even though my Node.js is installed on D:\NodeJS...

When I go to D:\NodeJS and try again to install robotjs I still get the same errors. But now at least it's not trying to install to my user folder.

Never knew NPM couldn't handle being invoked from a different folder.

**Comment by PinocchioStrings** [comment]
This from the debug log:

387 verbose pkgid robotjs@0.6.0
388 verbose cwd D:\NodeJS
389 verbose Windows_NT 10.0.19042
390 verbose argv "D:\\NodeJS\\node.exe" "D:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "robotjs"
391 verbose node v15.0.1
392 verbose npm  v7.0.3
393 error code 1
394 error path D:\NodeJS\node_modules\robotjs
395 error command failed
396 error command C:\WINDOWS\system32\cmd.exe /d /s /c "prebuild-install || node-gyp rebuild"
397 error gyp info it worked if it ends with ok
397 error gyp info using node-gyp@7.1.2
397 error gyp info using node@15.0.1 | win32 | x64
397 error gyp ERR! find Python
397 error gyp ERR! find Python Python is not set from command line or npm configuration
397 error gyp ERR! find Python Python is not set from environment variable PYTHON
397 error gyp ERR! find Python checking if "python3" can be used
397 error gyp ERR! find Python - "python3" is not in PATH or produced an error
397 error gyp ERR! find Python checking if "python" can be used
397 error gyp ERR! find Python - "python" is not in PATH or produced an error
397 error gyp ERR! find Python checking if "python2" can be used
397 error gyp ERR! find Python - "python2" is not in PATH or produced an error
397 error gyp ERR! find Python checking if Python is C:\Python37\python.exe
397 error gyp ERR! find Python - "C:\Python37\python.exe" could not be run
397 error gyp ERR! find Python checking if Python is C:\Python27\python.exe
397 error gyp ERR! find Python - "C:\Python27\python.exe" could not be run
397 error gyp ERR! find Python checking if the py launcher can be used to find Python
397 error gyp ERR! find Python - "py.exe" is not in PATH or produced an error
397 error gyp ERR! find Python
397 error gyp ERR! find Python **********************************************************
397 error gyp ERR! find Python You need to install the latest version of Python.
397 error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
397 error gyp ERR! find Python you can try one of the following options:
397 error gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
397 error gyp ERR! find Python   (accepted by both node-gyp and npm)
397 error gyp ERR! find Python - Set the environment variable PYTHON
397 error gyp ERR! find Python - Set the npm configuration variable python:
397 error gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
397 error gyp ERR! find Python For more information consult the documentation at:
397 error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
397 error gyp ERR! find Python **********************************************************
397 error gyp ERR! find Python
397 error gyp ERR! configure error
397 error gyp ERR! stack Error: Could not find any Python installation to use
397 error gyp ERR! stack     at PythonFinder.fail (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\find-python.js:302:47)
397 error gyp ERR! stack     at PythonFinder.runChecks (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
397 error gyp ERR! stack     at PythonFinder.<anonymous> (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\find-python.js:200:18)
397 error gyp ERR! stack     at PythonFinder.execFileCallback (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\find-python.js:266:16)
397 error gyp ERR! stack     at exithandler (node:child_process:316:5)
397 error gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:328:5)
397 error gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
397 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:275:12)
397 error gyp ERR! stack     at onErrorNT (node:internal/child_process:465:16)
397 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:80:21)
397 error gyp ERR! System Windows_NT 10.0.19042
397 error gyp ERR! command "D:\\NodeJS\\node.exe" "D:\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
397 error gyp ERR! cwd D:\NodeJS\node_modules\robotjs
397 error gyp ERR! node -v v15.0.1
397 error gyp ERR! node-gyp -v v7.1.2
397 error gyp ERR! not ok
398 verbose exit 1
